### ISSUE TITLE
Inquiry about experiment details

### ISSUE THREAD

**Issue by plusgrey** [jcorsetti/oryon.github.io#4]
Hi Jaime,

Thanks for your great work.  Could you please share how many GPUs are used and what type of GPU/TPU you use for training. 

There is one more small question, since the oryon is able to estimate postition of an object with a pose, is it possible to formulate it as a tracking model? For example, using the first frame of a video as the anchor and the rest frames are queries.

**Comment by plusgrey** [comment]
Moreover, when I run the training code. It shows a missing file error
![image](https://github.com/jcorsetti/oryon/assets/56119958/1dec4eef-37cd-4aa3-9550-c808f6c0d5dd)

I also found the dataset name of this line (https://github.com/jcorsetti/oryon/blob/81f676725ad90207c2ad2007dd843459df220395/prepare_sn6d.sh#L8) in the prepare_sn6d.sh should be shapenet6d.

**Comment by jcorsetti** [comment]
Thanks for your interest and sorry for the late reply. 
For training we used four Nvidia V100 GPU as detailed in Section 3.3 of the supplementary material, you can also check out that section for the execution times.
About the tracking question: yes, Oryon could definitely be applied in this context without changing the formulation, but I think that retraining on a dataset with same-scene pairs would be necessary.
Thanks for pointing out the two errors, I should have fixed them in the last commits.

**Comment by jcorsetti** [comment]
Feel free to reopen the issue if you have more questions about this.
